image: "harbor.sitronics-kt.dev/qa/qa-python-3.10:python-3.10.4"

stages:
  - linting
  - build
  - deploy

flake8:
    stage: linting
    tags: [docker-gitlabCI]
    script:
      - pip install flake8 flake8-variables-names flake8-quotes flake8-import-order flake8-commas flake8-builtins flake8-functions flake8-function-order flake8-functions-names
      - flake8 .
    only:
      - merge_requests

pylint:
    stage: linting
    tags: [docker-gitlabCI]
    script:
      - pip install pylint
      - find . -type f -name "*.py" | xargs pylint
    only:
      - merge_requests
